//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lib.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_karahi_Item
    {
        public int Id { get; set; }
        public string ItemName { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> Company { get; set; }
        public Nullable<int> Rid { get; set; }
    }
}
