//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lib.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Karahi_D
    {
        public int Id { get; set; }
        public Nullable<int> itemId { get; set; }
        public Nullable<double> Qty { get; set; }
        public string karahiNo { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Rid { get; set; }
        public Nullable<int> Compy { get; set; }
    }
}
